version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    restart: on-failure
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'password'

volumes:
  mongodb:
