version: '3.7'

services:
  mongodb:
    build: ./docker/Dockerfile.mongo-replica-set
    ports:
      - 27017:27017
    restart: on-failure
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_REPLICA_HOST: 'localhost'
      MONGO_REPLICA_PORT: 27017

volumes:
  mongodb:
